export const STRINGS = {
    // ── App shell ──────────────────────────────────────────────────────────────
    app_name:          'Mission Control',
    app_subtitle:      'Plataforma de Méritos y Aprendizaje en Equipo',
    sign_in_google:    'Iniciar sesión con Google',
    sign_in_short:     'Entrar',
    loading:           'Cargando…',
    platform_admin:    'Admin de Plataforma',
    switch_team:       'Cambiar Equipo',
    sign_out:          'Cerrar Sesión',
    exit_preview:      'Salir de Vista Previa',
    preview_as:        'Vista previa como…',
    preview_banner:    'Modo Vista Previa',
    expand_menu:       'Expandir menú',
    collapse_menu:     'Contraer menú',
    more_btn:          'Más',

    // ── Navigation ────────────────────────────────────────────────────────────
    nav_inicio:      'Inicio',
    nav_overview:    'Equipo',
    nav_feed:        'Feed',
    nav_channels:    'Canales',
    nav_categories:  'Áreas',
    nav_members:     'Miembros',
    nav_merits:      'Logros',
    nav_leaderboard: 'Posiciones',
    nav_calendar:    'Calendario',
    nav_tools:       'Herramientas',
    nav_academy:     'Academia',
    nav_funding:     'Fondos',
    nav_tasks:       'Tareas',
    nav_sessions:    'Sesiones',
    nav_knowledge_map: 'Mapa',
    nav_inventory:   'Inventario',
    nav_hr:          'Q&S',
    nav_myprofile:   'Perfil',
    nav_admin:       'Admin',
    nav_domain_comunidad:   'Comunidad',
    nav_domain_trabajo:     'Trabajo',
    nav_domain_aprendizaje: 'Aprendizaje',
    nav_domain_reconocimiento: 'Reconocimiento',
    nav_domain_admin:       'Admin',
    admin_only:      'Solo administradores',

    saving:          'Guardando…',

    // ── Admin (team dropdown options) ──────────────────────────────────────────
    admin_tab_title:       'Admin — Opciones de listas',
    admin_tab_help:        'Edita las opciones de los menús. Un valor por línea o separados por coma. Guarda en cada sección. Los puntos de logros del sistema (Actualización semanal, Perfil completo, 50 actualizaciones) y de tareas revisadas se aplican retroactivamente a todos los eventos existentes.',
    admin_careers_majors:  'Carreras / Majors',
    admin_semesters:       'Semestres',
    admin_personality_tags:'Etiquetas de personalidad',
    admin_personality_hint:'Diccionario: clave : texto mostrado. Una por línea. Ej: ptag_creative: Creativo/a. La clave se guarda; el texto es cómo se renderiza.',
    admin_collab_suggestions: 'Sugerencias de colaboración',
    admin_merit_tiers:     'Niveles de logro (tiers)',
    admin_empty_ok:        'Vacío está bien',
    admin_section_profile: 'Perfil',
    admin_section_profile_hint: 'Opciones del formulario de perfil: carreras, semestres, etiquetas de personalidad (diccionario tag:texto mostrado), sugerencias de colaboración.',
    admin_section_merits:  'Logros y méritos',
    admin_section_merits_hint: 'Tipos, dominios, niveles y puntos de logros automáticos (Actualización semanal, Perfil completo, 50 actualizaciones). Se aplican retroactivamente.',
    admin_section_tasks:  'Tareas',
    admin_section_tasks_hint: 'Puntos por calificación en el flujo "Solicitar Revisión". Se aplican retroactivamente.',
    admin_system_merit_points: 'Puntos de logros del sistema',
    admin_system_merit_hint: 'Actualización semanal, Perfil completo, 50 actualizaciones. Al guardar se aplican retroactivamente.',
    admin_system_weekly: 'Actualización semanal',
    admin_system_profile: 'Perfil completo',
    admin_system_milestone: '50 actualizaciones',
    admin_task_grade_points: 'Puntos por tarea revisada',
    admin_task_grade_points_hint: 'Individual = 1 asignado. Equipo = 2+ asignados. Se aplican retroactivamente.',
    admin_task_grade_individual: 'Individual',
    admin_task_grade_team: 'Equipo (por miembro)',
    admin_merit_families: 'Familias de mérito',
    admin_merit_families_hint: 'Una por línea: id: nombre o id: nombre — descripción. Para inferencia de trayectorias.',
    admin_knowledge_areas: 'Áreas de conocimiento',
    admin_knowledge_areas_hint: 'Una por línea: id: nombre. Para el mapa de conocimientos.',
    admin_domains_hint:       'Una por línea. Formato id: etiqueta (ej. physical: Componente físico) o texto plano.',
    admin_skill_proposals: 'Propuestas de habilidades',
    admin_skill_proposals_hint: 'Los miembros proponen habilidades que no están en el catálogo. Aprueba para agregarlas al diccionario.',
    approve: 'Aprobar',
    reject: 'Rechazar',
    admin_retroactive: 'Retroactivo',

    // ── Funding ────────────────────────────────────────────────────────────────
    funding_account_title:  'Cuenta donde se guarda el dinero',
    funding_accounts_title:  'Cuentas',
    funding_add_account:    'Agregar cuenta',
    funding_no_accounts:   'Sin cuentas. Agrega una para comenzar.',
    funding_grand_total:   'Total general',
    funding_account:       'Cuenta',
    funding_bank:           'Banco / Institución',
    funding_account_name:   'Nombre de la cuenta',
    funding_last4:          'Últimos 4 dígitos',
    funding_balance:        'Saldo actual',
    funding_no_account:     'Sin información de cuenta configurada.',
    funding_add_entry:      'Agregar movimiento',
    funding_date:           'Fecha',
    funding_description:    'Descripción',
    funding_amount:         'Monto',
    funding_type:           'Tipo',
    funding_type_in:        'Entrada',
    funding_type_out:       'Salida',
    funding_category:      'Categoría',
    funding_in:             'Entrada',
    funding_out:            'Salida',
    funding_no_entries:     'Sin movimientos registrados.',
    inventory_title:        'Inventario',
    inventory_help:         'Administra herramientas, consumibles y otros recursos por area.',
    inventory_add_item:     'Agregar item',
    inventory_leader_scope_hint: 'Como lider, solo puedes editar el inventario de tu area.',
    inventory_admin_scope_hint: 'Los admins pueden registrar inventario global o por area.',
    inventory_name:         'Nombre',
    inventory_quantity:     'Cantidad actual',
    inventory_quantity_label: 'Cantidad',
    inventory_unit:         'Unidad de medida',
    inventory_min_quantity: 'Minimo',
    inventory_notes:        'Notas',
    inventory_counters_help: 'Cantidad = cuantas unidades tienes. Unidad = como se mide, por ejemplo piezas, cajas o litros.',
    inventory_sheet_help:   'Se muestra una sola hoja. Usa los filtros para cambiar el area o tipo visible.',
    inventory_spreadsheet:  'Hoja de inventario',
    inventory_filter_area:  'Filtrar por area',
    inventory_filter_all_areas: 'Todas las areas',
    inventory_type:         'Tipo',
    inventory_available:    'Disponible',
    inventory_actions:      'Acciones',
    inventory_select_borrower: 'Seleccionar prestatario',
    inventory_register_loan: 'Registrar prestamo',
    inventory_loan_notes:   'Notas del prestamo',
    inventory_on_loan:      'Prestado',
    inventory_active_loans: 'Prestamos activos',
    inventory_due_date:     'Vence',
    inventory_open_calendar: 'Calendario',
    inventory_due_alerts:   'Alertas de prestamos',
    inventory_overdue_count: 'Prestamos vencidos',
    inventory_due_soon_count: 'Prestamos por vencer',
    inventory_overdue:      'Vencido',
    inventory_due_soon:     'Por vencer',
    inventory_no_due_date:  'Sin fecha limite',
    inventory_return:       'Registrar devolucion',
    inventory_empty:        'No hay items en este inventario todavia.',
    inventory_low_stock:    'Stock bajo',
    inventory_item_singular: 'item',
    inventory_item_plural:  'items',
    inventory_area_label:   'Area',
    inventory_area_global:  'General',
    inventory_filter_all:   'Todo',
    channels_title:         'Canales entre equipos',
    channels_help:          'Crea canales, invita equipos y coordina conversaciones compartidas.',
    channels_my_channels:   'Mis canales',
    channels_pending_invites: 'Invitaciones para mi equipo',
    channels_pending_invites_help: 'Aqui solo aparecen invitaciones pendientes dirigidas al equipo activo.',
    channels_new_channel:   'Nuevo canal',
    channels_name:          'Nombre del canal',
    channels_description:   'Descripción',
    channels_invite_teams:  'Invitar equipos',
    channels_create:        'Crear canal',
    channels_no_channels:   'No tienes canales aceptados todavía.',
    channels_no_pending:    'El equipo activo no tiene invitaciones pendientes.',
    channels_accept:        'Aceptar',
    channels_decline:       'Rechazar',
    channels_members:       'Equipos dentro',
    channels_pending:       'Pendientes',
    channels_add_invites:   'Invitar más equipos',
    channels_send:          'Enviar',
    channels_message_ph:    'Escribe un mensaje para el canal…',
    channels_empty_messages:'Aún no hay mensajes en este canal.',
    channels_invited_by:    'Invitado por',
    channels_owner:         'Canal propietario',
    channels_select_channel:'Selecciona un canal para ver la conversación.',

    // ── Team browser ──────────────────────────────────────────────────────────
    your_teams:           'Tus Equipos',
    pending_requests:     'Solicitudes Pendientes',
    join_a_team:          'Unirse a un Equipo',
    awaiting_approval:    'En espera de aprobación',
    requested_category:   'Área solicitada',
    review_shortly:       'Un admin del equipo revisará tu solicitud en breve.',
    request_to_join:      'Solicitar Unirse',
    create_new_team:      'Crear Nuevo Equipo',
    team_name_placeholder:'Nombre del equipo',
    create:               'Crear',
    no_teams:             'Aún no hay equipos. Contacta a tu Administrador de Plataforma.',
    no_teams_sign_in:     'Sin equipos aún. Inicia sesión y pide al Admin de Plataforma que cree uno.',
    rename_team:          'Renombrar',
    delete_team:          'Eliminar equipo',
    rename_team_ph:       'Nuevo nombre del equipo…',
    manage_teams:         'Administrar Equipos',

    // ── Common actions ────────────────────────────────────────────────────────
    edit:         'Editar',
    save:         'Guardar',
    save_failed:   'Error al guardar.',
    save_failed_image: 'La imagen puede ser muy grande — prueba con una foto más pequeña.',
    save_weekly_failed: 'Error al guardar el estatus semanal.',
    cancel:       'Cancelar',
    delete:       'Eliminar',
    add:          'Agregar',
    approve:      'Aprobar',
    reject:       'Rechazar',
    close:        'Cerrar',
    back:         'Volver',
    view_profile: 'Ver perfil',
    click_to_edit:'Ver y editar mi perfil →',

    // ── Overview ──────────────────────────────────────────────────────────────
    overview_title:     'Resumen del Equipo',
    tagline:            'Eslogan',
    about:              'Acerca de',
    history:            'Historia',
    objectives:         'Objetivos',
    kpis:               'KPIs / Métricas',
    add_kpi:            '+ Agregar KPI',
    total_members:      'Miembros Totales',
    active_merits:      'Logros Activos',
    modules_completed:  'Módulos Completados',
    active:             'activos',
    edit_overview:      'Editar Resumen',
    total_points_earned:     'Puntos Totales Obtenidos',
    avg_points_per_member:  'Puntos Promedio por Miembro',
    avg_points_by_area:     'Puntos promedio por área',
    stats_filter_group:    'Analizar por grupo',
    stats_filter_all:      'Todo el equipo',
    stats_view_global:     'Global',
    stats_view_area:       'Por área',
    stats_view_status:     'Por nivel',
    stats_select_area:     'Seleccionar área…',
    stats_select_status:   'Seleccionar nivel…',
    stats_no_members:      'Sin miembros activos en este grupo.',
    avg_points_by_level:    'Puntos promedio por nivel',
    std_deviation:          'Desv. estándar',
    points_distribution:    'Distribución de puntos',
    click_for_details:      'Clic para ver desglose',

    // ── My commitments (responsibility dashboard) ───────────────────────────────
    my_commitments:         'Mis compromisos',
    my_commitments_desc:    'Tu vista de responsabilidades. Revisa con regularidad.',
    my_pending_tasks:      'Tareas pendientes',
    my_overdue_tasks:      'Tareas vencidas',
    weekly_streak:         'Racha semanal',
    weekly_this_week:      'Esta semana',
    week_prev:             'Semana anterior',
    week_next:             'Semana siguiente',
    weekly_posted:         'Publicado',
    weekly_not_posted:     'Sin publicar',
    profile_completion:    'Perfil',
    profile_complete_pct:  'completo',
    view_tasks:            'Ver tareas',
    view_profile:          'Ver perfil',
    task_overdue_by:       'Vencida hace',
    task_overdue_days:     'días',
    task_status_assigned:  'Asignada',
    task_status_blocked:   'Bloqueada',
    task_status_in_progress:'En progreso',
    task_status_pending_review:'Pendiente de revisión',
    task_status_completed: 'Completada',
    task_no_tasks_guidance:'No tienes tareas asignadas. Consulta con tu líder.',
    task_no_pending_guidance:'Al día. Publica tu actualización semanal en Mi Perfil.',
    feed_no_posts_guidance:'Aún no hay publicaciones. Sé el primero en compartir.',
    leaderboard_by_effort: 'Por esfuerzo',
    leaderboard_by_points:  'Por puntos',
    leaderboard_weekly_count:'Actualizaciones',
    leaderboard_tasks_done:'Tareas completadas',
    leaderboard_effort:     'Esfuerzo',
    export_my_record:      'Exportar mi registro',
    export_merits:         'Méritos',
    export_tasks:          'Tareas',
    search_placeholder:   'Buscar tareas…',
    search_no_results:   'Ningún resultado.',
    inicio_desc:         'Tu panel personal. Acceso rápido a cambios y compromisos.',
    inicio_link_team_card:'Tarjeta del equipo',
    inicio_link_activity:'Actividad reciente',
    inicio_link_tasks:   'Tareas asignadas',
    inicio_no_membership:'Tu membresía está pendiente de aprobación.',
    inicio_summary_7d:  'Últimos 7 días',
    inicio_personal:    'Tu resumen',
    inicio_team:       'Resumen del equipo',
    inicio_merits_count: 'logros otorgados',
    inicio_merit_count:  'logro otorgado',
    inicio_my_merits:   'logros que recibiste',
    inicio_my_merit:    'logro que recibiste',
    inicio_you_received:'Recibiste',
    inicio_points_total: 'pts en total',
    inicio_tasks_to_you: 'tareas asignadas a ti',
    inicio_task_to_you:  'tarea asignada a ti',
    inicio_posts_count:  'publicaciones en el Feed',
    inicio_post_count:  'publicación en el Feed',
    inicio_activity:    'Actividad reciente',
    inicio_since_visit:  'Desde tu última visita',
    inicio_merit_awarded:'recibió',
    inicio_task_assigned:'Te asignaron',
    inicio_posts_feed:   'nuevas publicaciones en el Feed',
    inicio_post_feed:    'nueva publicación en el Feed',
    inicio_sessions_count: 'sesiones programadas',
    inicio_session_count:  'sesión programada',
    inicio_session_created: 'Nueva sesión',
    inicio_no_activity:  'Sin actividad reciente.',
    total_modules:      'Módulos Totales',
    kpi_label:          'Métrica',
    kpi_value:          'Valor',
    no_overview:        'Sin resumen configurado aún.',

    // ── Áreas (divisiones del equipo; interno: categories) ─────────────────────
    categories_title: 'Áreas',
    add_category:     'Agregar Área',
    category_name:    'Nombre del área',
    description:      'Descripción (opcional)',
    no_categories:    'Aún no hay áreas.',
    no_members_cat:   'Sin miembros en esta área.',
    cat_placeholder:  'ej. Mecánica',
    desc_placeholder: 'Descripción…',
    member_s:         'miembros',
    no_members_yet:   'Sin miembros aún',
    add_cat_name:     'Nombre de la nueva área',
    edit_category:    'Editando:',
    update_category:  'Actualizar',
    no_members_here:  'Aún no hay miembros en esta área.',
    update_cat:       'Actualizar',

    // ── Members ───────────────────────────────────────────────────────────────
    members_title:        'Miembros',
    pending_join_requests:'Solicitudes de Ingreso Pendientes',
    active_members:       'Miembros Activos',
    suspended_members:    'Miembros Suspendidos',
    add_ghost_member:     '+ Agregar Miembro Fantasma',
    ghost_name:           'Nombre para mostrar',
    unassigned:           'Sin asignar',
    strikes:              'faltas',
    add_strike:           '+Falta',
    remove_strike:        '-Falta',
    add_strike_evidence_title: 'Agregar falta con evidencia',
    add_strike_evidence_hint:  'Agrega al menos una: texto o enlace.',
    add_strike_for:       'Miembro',
    strike_evidence_text: 'Texto o descripción',
    strike_evidence_text_ph: 'Ej. Falta de asistencia a reunión del 3/3…',
    strike_evidence_link:  'Enlace',
    strike_evidence_link_ph: 'https://…',
    strike_evidence_title: 'Evidencias de faltas',
    strike_evidence_strike: 'Falta',
    strike_evidence_added_by: 'Agregada por',

    // ── Q&S (Quejas y Sugerencias) ────────────────────────────────────────────
    hr_page_title:            'Quejas y Sugerencias',
    hr_suggestions:           'Sugerencias',
    hr_complaints:            'Quejas',
    hr_suggestions_submit:    'Enviar sugerencia',
    hr_suggestion_placeholder:'Tu sugerencia para mejorar el equipo…',
    hr_suggestion_anonymous:  'Enviar de forma anónima',
    hr_suggestion_submit:     'Enviar',
    hr_suggestions_list:      'Sugerencias recibidas',
    hr_anonymous:             'Anónimo',
    hr_no_suggestions:        'Aún no hay sugerencias.',
    hr_complaints_submit:     'Enviar queja',
    hr_complaint_non_anonymous: 'Las quejas no pueden ser anónimas (responsabilidad). Solo el asesor académico puede ver quién envió cada queja.',
    hr_complaint_type:       'Tipo de queja',
    hr_complaint_type_team:   'Equipo',
    hr_complaint_type_area:   'Área',
    hr_complaint_type_person: 'Persona',
    hr_complaint_target_area: 'Área',
    hr_complaint_target_person:'Persona',
    hr_complaint_content:    'Descripción',
    hr_complaint_content_ph:  'Describe la situación…',
    hr_complaint_evidence:    'Evidencia (texto o enlace)',
    hr_complaint_submit:      'Enviar queja',
    hr_complaints_list:       'Quejas recibidas',
    hr_no_complaints:         'Aún no hay quejas.',
    hr_evidence_required:     'Se requiere al menos una evidencia.',
    hr_complaint_evidence_required: 'La queja requiere descripción y evidencia.',
    hr_complaint_select_area: 'Selecciona un área.',
    hr_complaint_select_person: 'Selecciona una persona.',
    hr_complaints_count:      'Quejas',
    hr_my_suggestions_posted:  'Mis sugerencias enviadas',
    hr_my_suggestions_implemented: 'Implementadas',
    hr_suggestions_pending:   'Pendientes',
    hr_suggestions_accepted:  'Aceptadas',
    hr_suggestions_dismissed: 'Descartadas',
    hr_suggestions_all:       'Todas',
    hr_suggestions_consider:  'Considerar',
    hr_suggestions_dismiss:   'Descartar',
    hr_suggestions_reconsider:'Reconsiderar',
    hr_suggestions_accept_points: 'Elegir puntos para la sugerencia aceptada',
    hr_suggestion_anonymous_no_merit: 'Las sugerencias anónimas no pueden recibir mérito.',
    hr_suggestion_author_not_found: 'No se encontró al autor de la sugerencia.',
    role_label:           'Rol',
    suspend:              'Suspender',
    restore:              'Reactivar',
    no_active:            'Aún no hay miembros activos.',
    no_suspended:         'No hay miembros suspendidos.',
    ghost_note:           '(sin cuenta)',
    motivation_label:     'Motivación',
    assign_category:      'Área',
    change_role:          'Rol',
    add_faculty_ghost:    '+ Agregar Asesor / Perfil Externo',
    new_ghost_form_title: 'Nuevo Perfil Externo (sin cuenta requerida)',
    full_name_req:        'Nombre completo *',
    no_category_opt:      'Sin área',
    brief_bio_ph:         'Bio breve (opcional)',
    create_profile_btn:   'Crear Perfil',
    wants_to_join:        'Quiere unirse a:',
    no_cat_selected:      'Sin área seleccionada',
    search_name:          'Buscar por nombre…',
    all_roles:            'Todos los roles',
    all_categories_opt:   'Todas las áreas',
    all_strikes:          'Todas las faltas',
    all_complaints:      'Todas',
    filter_strikes_0:    '0 faltas',
    filter_strikes_1:    '1 falta',
    filter_strikes_2:    '2 faltas',
    filter_strikes_3:    '3 faltas',
    filter_complaints_none: 'Sin quejas',
    filter_complaints_any:  'Con quejas',
    clear_filters:        'Limpiar',
    showing_of:           'miembros',
    th_member:            'Miembro',
    th_role:              'Rol',
    th_category:          'Área',
    th_strikes:           'Faltas',
    sort_by:               'Ordenar por',
    sort_asc:              'Ascendente',
    sort_desc:             'Descendente',
    th_action:            'Acción',
    external_badge:       '(externo)',
    no_members_filter:    'Ningún miembro coincide con los filtros.',
    suspended_header:     'Suspendidos',
    reinstate:            'Reactivar',

    // ── Logros (antes Méritos) ─────────────────────────────────────────────────
    merits_title:          'Logros y Reconocimientos',
    define_merit:          'Definir un nuevo logro',
    logo:                  'Logo',
    pick_emoji:            'Elegir emoji ▾',
    pick_icon:             'Elegir icono ▾',
    paste_image_url:       'URL de imagen…',
    reframe:               '↻',
    name:                  'Nombre',
    points:                'Puntos',
    points_placeholder:    'ej. 100',
    category:              'Área',
    global_category:       'Global (cualquier área)',
    add_merit:             'Agregar Logro',
    merit_definitions:     'Definiciones de Logros',
    no_merits:             'Aún no hay logros definidos.',
    award_merit:           'Otorgar un Logro',
    member:                'Miembro',
    merit:                 'Logro',
    select_member:         'Seleccionar miembro…',
    member_search_placeholder: 'Buscar miembro…',
    select_merit:          'Seleccionar logro…',
    merit_search_placeholder: 'Buscar por nombre, descripción, etiquetas…',
    merit_scope_all:       'Todos los ámbitos',
    merit_tag_all:         'Todas las etiquetas',
    no_merits_match:      'Ningún logro coincide con los filtros.',
    merit_tags:            'Etiquetas (para búsqueda)',
    merit_tags_placeholder:'ej. mecánica, software…',
    merit_attr_types:      'Tipo (para búsqueda)',
    merit_attr_domains:    'Categoría',
    merit_attr_tier:       'Nivel',
    merit_attr_families:   'Familias',
    merit_attr_knowledge_areas: 'Áreas de conocimiento',
    knowledge_map_hint:    'Vista derivada solo de módulos aprobados. Permite revisar skills por usuario y usuarios por skill con filtros.',
    knowledge_map_all_areas: 'Todas las áreas',
    knowledge_map_all_types: 'Todos los tipos',
    knowledge_map_no_areas: 'Configura las áreas de conocimiento en Admin para ver el mapa.',
    knowledge_map_no_evidence: 'No hay módulos aprobados que coincidan con los filtros actuales.',
    merit_filter_scope:    'Ámbito',
    merit_filter_type:     'Tipo',
    merit_filter_domain:   'Categoría',
    merit_filter_tier:     'Nivel',
    merit_repeatable:      'Se puede otorgar varias veces',
    merit_award_once_error:'Este logro solo se puede otorgar una vez por persona. Ya fue otorgado a este miembro.',
    merit_self_award_error:'No puedes otorgarte logros a ti mismo.',
    merit_type_technical:  'Técnico',
    merit_type_leadership: 'Liderazgo',
    merit_type_collaboration: 'Colaboración',
    merit_type_innovation: 'Innovación',
    merit_type_milestone:  'Hito',
    merit_type_research:   'Investigación',
    merit_type_communication: 'Comunicación',
    merit_type_documentation: 'Documentación',
    merit_type_presentation: 'Presentación',
    merit_type_other:      'Otro',
    merit_type_técnico:    'Técnico',
    merit_type_liderazgo:  'Liderazgo',
    merit_type_colaboración:'Colaboración',
    merit_type_innovación:  'Innovación',
    merit_type_hito:       'Hito',
    merit_type_investigación:'Investigación',
    merit_type_comunicación:'Comunicación',
    merit_type_documentación:'Documentación',
    merit_type_presentación:'Presentación',
    merit_type_otro:       'Otro',
    merit_domain_software: 'Software',
    merit_domain_hardware: 'Hardware',
    merit_domain_mechanical: 'Mecánica',
    merit_domain_electronics: 'Electrónica',
    merit_domain_design:   'Diseño',
    merit_domain_research: 'Investigación',
    merit_domain_general:  'General',
    merit_domain_mecánica:  'Mecánica',
    merit_domain_electrónica:'Electrónica',
    merit_domain_diseño:   'Diseño',
    merit_domain_investigación:'Investigación',
    merit_tier_bronze:     'Bronce',
    merit_tier_silver:     'Plata',
    merit_tier_gold:       'Oro',
    merit_tier_bronce:     'Bronce',
    merit_tier_plata:      'Plata',
    merit_tier_oro:        'Oro',
    evidence_optional:     'URL o descripción…',
    award:                 'Otorgar',
    merit_audit_log:       'Registro de Logros',
    platform_admin_editable:'Admin de Plataforma: las filas son editables',
    platform_config_reset:  'Restaurar',
    platform_config_min_one:'Cada lista debe tener al menos un valor.',
    pts_label:             'pts',
    short_description:     'Descripción breve',
    long_description:      'Cómo obtenerlo',
    short_desc_placeholder:'Resumen corto (máx. 100 caracteres)…',
    long_desc_placeholder: 'Describe en detalle cómo ganar este mérito…',
    merit_detail_close:    'Cerrar',
    merit_click_to_view:   'Clic para ver descripción',
    how_to_obtain:         'Cómo Obtenerlo',
    no_long_desc:          'Sin descripción detallada.',
    no_events_yet:         'Aún no hay logros otorgados.',
    th_when:               'Cuándo',
    th_note:               'Nota',
    th_type:               'Tipo',
    note_ph:               'Nota / razón',
    revoke:                'Revocar',
    revoke_confirm:        '¿Eliminar permanentemente este registro de logro? Esta acción no se puede deshacer.',
    merit_delete_confirm:  '¿Eliminar este logro? Esta acción no se puede deshacer.',
    merit_recover_title:   'Logros eliminados con premios existentes',
    merit_recover_hint:    'Estos logros fueron eliminados pero aún tienen premios asignados. Puedes recuperarlos para que vuelvan a aparecer en las definiciones.',
    merit_recover_btn:     'Recuperar',
    merit_recover_no_data: 'No hay datos suficientes para recuperar este logro.',
    merit_recover_failed:  'No se pudo recuperar el logro.',
    delete_matrix_confirm: '¿Eliminar esta matriz? Esta acción no se puede deshacer.',
    assignable_by:          'Solo puede otorgar',
    assignable_by_leader:   'Líder',
    assignable_by_teamAdmin:'Team Admin',
    assignable_by_facultyAdvisor: 'Faculty Advisor',
    awarded_by:            'Reconocido por',
    merit_awarded_by_system:'Sistema',
    merit_leader_area_only: 'Como Líder solo puedes otorgar reconocimiento a miembros de tu área.',
    no_assignable_logros:   'No tienes asignados logros que puedas otorgar (solo puedes otorgar los que coinciden con tu rol).',

    // ── Leaderboard ───────────────────────────────────────────────────────────
    leaderboard_title: 'Leaderboard',
    all_time:          'Histórico',
    season_3mo:        'Temporada (3 meses)',
    rank_label:        '#',
    no_leaderboard:    'Aún no hay logros registrados.',
    this_season:       'Esta Temporada (3 meses)',
    all_time_tab:      'Histórico',
    no_merit_data:     'Aún no hay datos de logros. ¡Otorga algunos logros para ver el ranking!',

    // ── Academy ───────────────────────────────────────────────────────────────
    academy_title:        'Academia',
    new_module:           'Nuevo Módulo',
    module_title:         'Título',
    module_desc:          'Descripción',
    module_content:       'Contenido / Lectura',
    video_url:            'URL de Video (YouTube/Vimeo)',
    retrieval_prompt:     'Pregunta de recuperación',
    submit:               'Enviar',
    completed:            'Completado',
    start_module:         'Iniciar →',
    no_modules:           'Aún no hay módulos.',
    add_module:           'Agregar Módulo',
    module_order:         'Orden',
    watch_video:          'Ver Video',
    your_answer:          'Tu respuesta…',
    completed_on:         'Completado el',
    delete_module:        'Eliminar',
    edit_module:          'Editar',
    save_module:          'Guardar Módulo',
    new_module_form_title:'Nuevo Módulo',
    title_req:            'Título *',
    short_desc_mod:       'Descripción breve',
    content_ph:           'Contenido / material de lectura',
    video_ph:             'URL de Video — pega enlace de YouTube o Vimeo',
    embed_label:          'Embed:',
    url_parse_err:        'No se pudo analizar la URL',
    retrieval_ph:         'Pregunta de recuperación — los miembros deben responderla para completar el módulo *',
    modules_list:         'Módulos',
    select_module_msg:    'Selecciona un módulo de la lista.',
    retrieval_label:      'Pregunta de recuperación:',
    must_submit_msg:      'Debes enviar una respuesta para marcar esto como completado.',
    mark_complete:        'Marcar como Completado',
    edit_module_title:    'Editar Módulo',
    topic_label:          'Tema',
    add_topic:            'Agregar tema',
    topic_title_ph:       'Título del tema',
    request_review:       'Solicitar revisión',
    review_requested:     'Revisión solicitada',
    review_approved:      'Aprobado',
    academy_eval_personal:'La evaluación es personal; un mentor te revisará.',

    // ── Tasks ─────────────────────────────────────────────────────────────
    task_assign:         'Asignar tarea',
    task_assign_to:      'Asignar a',
    task_title:         'Título',
    task_title_ph:       'Título de la tarea…',
    task_description:    'Descripción',
    task_description_ph: 'Detalles (opcional)…',
    task_due:            'Fecha límite',
    task_my_pending:     'Mis tareas pendientes',
    task_pending:        'Pendientes',
    task_all_team:      'Todas las tareas del equipo',
    task_no_pending:     'No tienes tareas pendientes.',
    task_completed:      'Completadas',
    task_mark_done:      'Marcar hecha',
    task_assigned_by:    'Asignada por',
    task_assigned_to:    'Asignada a',
    task_assign_search:  'Escribe nombre para buscar…',
    task_assign_no_match:'Sin coincidencias',
    task_assign_your_area:'Solo tu área',
    task_assign_hint:    'Escribe para buscar por nombre. Haz clic en un resultado para asignar (puedes elegir varios).',
    task_assign_type_to_search: 'Escribe al menos 1 carácter para ver resultados.',
    task_assign_selected:'Seleccionados',
    task_filter_area:    'Todas las áreas',
    task_from_pm_tools:  'Las tareas se crean desde herramientas de gestión de proyecto (p. ej. tableros SCRUM).',
    task_request_review:   'Solicitar Revisión',
    task_cancel_submission:'Cancelar envío',
    task_waiting_review:   'En espera de revisión por el responsable.',
    task_review_responsible: 'Revisión a cargo de',
    task_pending_your_review: 'Pendientes de tu revisión',
    task_assign_merit:     'Asignar logro…',
    task_assign_merit_hint: 'Elige un logro del catálogo para asignar. Los puntos los define el admin.',
    task_assigned_merit_label: 'Logro asignado',
    task_grade_label:     'Calificación',
    task_grade_hint:      'Califica el trabajo completado.',
    task_accepted_at:     'Aceptada',
    task_acceptance_time: 'Tiempo hasta aceptación',
    task_reject_review:   'Rechazar entrega',
    task_reject_prompt:   'Explica por qué la entrega está incompleta o no cumple el estándar.',
    task_review_feedback: 'Feedback de revisión',
    task_grade_ok:        'Ok',
    task_grade_good:      'Bien',
    task_grade_excellent: 'Excelente',
    task_grade_perfect:   'Perfecto',
    task_mark_blocked:    'Marcar bloqueada',
    task_unblock:         'Desbloquear',
    task_blocked_reason_ph:'Motivo del bloqueo (opcional)…',
    task_responsibility_history: 'Tu historial de compromisos',

    // ── Sessions ───────────────────────────────────────────────────────────────
    session_title:       'Sesiones',
    session_new:         'Nueva sesión',
    session_edit:        'Editar sesión',
    session_class:       'Clase',
    session_type:        'Tipo',
    session_scheduled:   'Fecha y hora',
    session_duration:    'Duración (min)',
    session_place:       'Lugar',
    session_description: 'Descripción',
    session_short_description: 'Descripción corta',
    session_long_description: 'Descripción larga',
    session_attendance:  'Asistencia',
    session_attendance_all: 'Todos',
    session_attendance_attended: 'Asistieron',
    session_attendance_not_attended: 'No asistieron',
    session_take_attendance: 'Tomar asistencia',
    session_save_attendance: 'Guardar asistencia',
    session_grants_points: 'Otorgar puntos por asistencia',
    session_points_after_attendance: 'Los puntos se asignan cuando guardas la asistencia de la sesión.',
    session_points_amount: 'Puntos por asistencia',
    session_no_sessions: 'No hay sesiones. Crea una para comenzar.',
    session_artifact_urls: 'Enlaces (URLs externas)',
    session_notes:       'Notas (post-sesión)',

    // ── Tools ─────────────────────────────────────────────────────────────────
    tools_title:       'Herramientas',
    team_tools_title:  'Herramientas del Equipo',
    tools_group_identify_plan: 'Identificar y planear',
    tools_group_execute:      'Ejecutar',
    calendar_title:    'Calendario',
    swot_title:        'Análisis FODA',
    kanban_title:      'Tableros Kanban',
    scrum_title:       'Tableros SCRUM',
    sprint_title:      'Tableros de Sprint',
    meetings_title:    'Notas de Reunión',
    goals_title:       'Objetivos / OKRs',
    strengths:         'Fortalezas',
    weaknesses:        'Debilidades',
    opportunities:     'Oportunidades',
    threats:           'Amenazas',
    add_event:         '+ Agregar Evento',
    event_title:       'Título del evento',
    event_date:        'Fecha',
    no_events:         'Aún no hay eventos. Agrega uno arriba.',
    event_title_label: 'Título del evento',
    event_title_ph:    'ej. Inicio de Temporada de Construcción',
    event_desc_opt:    'Descripción (opcional)',
    add_event_btn:     'Agregar Evento',
    no_events_add:     'Aún no hay eventos. Agrega uno arriba.',
    past_label:        'Pasado',
    swot_desc:          'Análisis FODA colaborativo para la estrategia del equipo.',
    edit_swot_btn:      'Editar FODA',
    new_swot_btn:       'Nueva FODA',
    swot_new_entry:     'Análisis FODA',
    swot_name_ph:       'ej. Proyecto X, Estrategia Q1',
    swot_strengths:     'Fortalezas',
    swot_weaknesses:    'Debilidades',
    swot_opportunities: 'Oportunidades',
    swot_threats:       'Amenazas',
    nothing_yet:        'Nada agregado aún.',
    add_item_btn:       '+ Agregar elemento',
    edit_swot:          'Editar',
    col_todo:           'Por Hacer',
    col_inprogress:     'En Progreso',
    col_done:           'Hecho',
    col_done_check:     'Hecho',
    col_backlog:        'Product Backlog',
    col_sprint:         'Sprint Backlog',
    no_kanban:          'Aún no hay tableros Kanban.',
    no_sprints:         'Aún no hay sprints.',
    sprint_ph:          'Nombre del sprint (ej. Sprint 1)',
    col_went_well:      'Salió Bien',
    col_improve:        'Por Mejorar',
    col_actions:        'Acciones',
    no_retros:          'Aún no hay retrospectivas.',
    retro_ph:           'Nombre (ej. Retro Sprint 1)',
    delete_board_btn:   'Eliminar tablero',
    add_col_btn:        '+ Agregar columna',
    new_board_btn:      'Nuevo tablero',
    board_name_ph:      'Nombre del tablero',
    card_ph:            'Título de la tarjeta…',
    move_to:            '→',
    add_card_ph:        'Agregar tarjeta…',
    create_board_btn:   'Crear',
    create_above:       ' Crea uno arriba.',
    create_new:         'Crear nuevo',
    tools_create_leader_only: 'Solo líderes y superiores pueden crear nuevas entradas.',
    add_column:         '+ Agregar columna',
    new_board:          'Nuevo tablero',
    board_name_placeholder:'Nombre del tablero',
    card_placeholder:   'Título de la tarjeta…',
    delete_board:       'Eliminar tablero',
    no_meetings:          'Aún no hay reuniones registradas.',
    new_meeting:          'Nueva Reunión',
    meeting_title:        'Título de la reunión',
    meeting_date:         'Fecha',
    meeting_notes:        'Notas',
    save_meeting:         'Guardar',
    action_items_label:   'Puntos de Acción',
    add_action_ph:        'Agregar punto de acción…',
    tbd_label:            'Por definir',
    action_done_of:       'puntos de acción listos',
    new_meeting_btn:      'Nueva Reunión',
    add_meeting_btn:      'Agregar Reunión',
    meeting_title_ph:     'Título de la reunión',
    attendees_ph:         'Asistentes',
    notes_ph:             'Notas / agenda de la reunión…',
    no_meetings_add:      'Aún no hay reuniones registradas. Agrega una arriba.',
    no_goals:          'Aún no hay objetivos.',
    new_goal:          'Nuevo Objetivo',
    goal_title:        'Título del objetivo',
    goal_status:       'Estado',
    goal_due:          'Fecha límite',
    goal_notes:        'Notas',
    save_goal:         'Guardar',
    new_goal_btn:      'Nuevo Objetivo',
    add_goal_btn:      'Agregar Objetivo',
    goal_ph:           'Objetivo (ej. Ganar el Campeonato Regional)',
    owner_ph:          'Responsable',
    no_goals_add:      'Aún no hay objetivos. Agrega uno arriba.',
    completed_badge:   'Completado',
    key_result_s:      'resultados clave',
    reopen_btn:        'Reabrir',
    complete_btn:      'Completar',
    overall_progress:  'Progreso general',
    key_results_label: 'Resultados Clave',
    add_kr_ph:         'Agregar resultado clave…',
    tab_calendar: 'Calendario',
    tab_swot:     'FODA',
    tab_kanban:   'Kanban',
    tab_scrum:    'Scrum Sprint',
    tab_retro:    'Retrospectiva',
    tab_meetings: 'Notas de Reunión',
    tab_goals:    'Objetivos / OKRs',
    tab_eisenhower: 'Matriz Eisenhower',
    tab_pugh:     'Matriz de Pugh',

    // ── Tools — etiqueta de instrucciones ────────────────────────────────────
    how_to_use: 'Cómo usar esta herramienta',

    // ── Tools — scope & last-edited ───────────────────────────────────────────
    scope_global:         'Global (todos los miembros)',
    scope_category:       'Área:',
    scope_label:          'Alcance',
    scope_select_ph:      'Seleccionar alcance…',
    scope_filter_all:     'Todo accesible',
    scope_filter_global:  'Solo Global',
    calendar_filter_all:  'Todos',
    calendar_filter_birthdays: 'Cumpleaños',
    last_edited_by:       'Última edición',
    last_edited_never:    'Nunca editado',
    category_only_hint:   'Solo visible para miembros de esta área',
    no_access_tool:       'No tienes acceso a esta herramienta.',
    can_edit_scope_hint:  'Solo líderes y admins de esta área pueden editar.',

    // ── Tools — descripciones de uso ─────────────────────────────────────────
    tool_desc_calendar:
      'Registra eventos, competencias, fechas límite e hitos del equipo.\n\n• Global: visible para todos los miembros.\n• Por área: solo visible para esa categoría.\n• Cumpleaños: se añaden automáticamente cuando los miembros completan su fecha de nacimiento en el perfil.\n\nMarca la casilla para ver cumpleaños (global o por área).',
    tool_desc_swot:
      'Análisis FODA: mapea Fortalezas, Oportunidades, Debilidades y Amenazas del equipo para guiar sesiones de planeación estratégica.\n\nSiempre global. El resultado alimenta el plan con Eisenhower o Pugh.',
    tool_desc_kanban:
      'Visualiza el trabajo en columnas: Por Hacer → En Progreso → Hecho.\n\n• Añade tarjetas con el campo de texto.\n• Usa "Asignar" para crear tareas: escribe en la barra de búsqueda, filtra por área si eres admin, haz clic en el nombre.\n• Arrastra conceptualmente con "Mover a" entre columnas.',
    tool_desc_scrum:
      'Ejecuta Sprints ágiles: Product Backlog → Sprint Backlog → En Progreso → Hecho.\n\n• Cada tablero = un Sprint.\n• Asignar tarea: barra de búsqueda, escribe nombre, clic para asignar.\n• Los asignados ven la tarea en la pestaña Tareas y pueden solicitar revisión.',
    tool_desc_retro:
      'Retrospectiva tras cada Sprint.\n\n• Qué salió bien: celebra éxitos.\n• Qué mejorar: identifica problemas.\n• Acciones: tareas concretas para el siguiente ciclo.\n\nUsa el resultado para planear el siguiente Sprint.',
    tool_desc_meetings:
      'Registra reuniones con agenda, asistentes y notas.\n\n• Lista de puntos de acción: cada uno se puede marcar completado.\n• Alcance global o por área según visibilidad.',
    tool_desc_goals:
      'Objetivos y Resultados Clave (OKRs).\n\n• Objetivo: meta cualitativa (ej. "Lanzar MVP").\n• Resultados clave: métricas medibles con barra de progreso.\n• Ajusta la barra según avance real.',
    tool_desc_eisenhower:
      'Matriz de priorización por urgencia e importancia.\n\n• Cuadrante 1: urgente e importante (hacer hoy).\n• Cuadrante 2: importante, no urgente (programar).\n• Cuadrante 3: urgente, no importante (delegar).\n• Cuadrante 4: ninguna (eliminar o posponer).',
    tool_desc_pugh:
      'Compara alternativas contra una opción de referencia.\n\n• Referencia: opción actual o baseline.\n• Alternativas: A, B, C…\n• Criterios: costo, tiempo, calidad…\n• Puntúa +1 (mejor), 0 (igual), -1 (peor). La opción con mayor total gana.',

    tool_example:     'Ejemplo',
    tool_more_info:   'Más información',
    tool_desc_kanban_example: 'Escribe "María" en la barra de búsqueda, filtra por área si tienes varias, haz clic en el nombre para asignar. La tarea aparecerá en la pestaña Tareas del asignado.',
    tool_desc_kanban_link: 'https://es.wikipedia.org/wiki/Kanban',
    tool_desc_scrum_example: 'Crea un Sprint "Q1 Semana 3", añade tarjetas al backlog, asigna con la búsqueda (ej. "Carlos"), mueve las tarjetas entre columnas según avance.',
    tool_desc_scrum_link: 'https://www.scrum.org/resources/what-is-scrum',
    tool_desc_retro_example: 'Tras un Sprint, añade puntos en "Qué salió bien" y "Qué mejorar", luego crea acciones concretas en la tercera columna.',
    tool_desc_retro_link: 'https://www.atlassian.com/team-playbook/plays/retrospective',
    tool_desc_swot_example: 'Fortalezas: "Equipo con experiencia en Python". Debilidades: "Falta documentación". Oportunidades: "Nuevo cliente potencial". Amenazas: "Competencia fuerte".',
    tool_desc_swot_link: 'https://es.wikipedia.org/wiki/An%C3%A1lisis_DAFO',
    tool_desc_eisenhower_example: 'Urgente e importante: bug en producción. Importante no urgente: refactorizar módulo. Urgente no importante: reunión que puede delegar. Ninguna: tarea obsoleta.',
    tool_desc_eisenhower_link: 'https://es.wikipedia.org/wiki/Matriz_de_Eisenhower',
    tool_desc_pugh_example: 'Referencia: "Sistema actual". Alternativas: A (Cloud), B (On-premise). Criterios: costo, escalabilidad, mantenimiento. Puntúa +1/-1 y suma.',
    tool_desc_pugh_link: 'https://en.wikipedia.org/wiki/Pugh_control',
    tool_desc_goals_example: 'Objetivo: "Lanzar MVP en Q1". Resultados clave: "Completar 10 user stories", "Tests al 80%". Ajusta la barra de progreso según avance.',
    tool_desc_goals_link: 'https://es.wikipedia.org/wiki/Objetivos_y_resultados_clave',
    tool_desc_calendar_example: 'Evento global: "Competencia regional - 15 Mar". Evento por área: "Revisión de diseño Mecánica - 20 Mar" con alcance Mecánica.',
    tool_desc_calendar_link: 'https://es.wikipedia.org/wiki/Calendario',
    tool_desc_meetings_example: 'Registra agenda, asistentes y notas. Marca los puntos de acción como completados cuando se cumplan.',
    tool_desc_meetings_link: 'https://www.atlassian.com/team-playbook/plays/meeting-notes',

    eisenhower_do_first:  'Hacer primero',
    eisenhower_schedule:  'Programar',
    eisenhower_delegate:  'Delegar',
    eisenhower_eliminate: 'Eliminar',
    eisenhower_urgent:    'Urgente',
    eisenhower_important:'Importante',
    eisenhower_add_item:  'Agregar elemento',
    eisenhower_new_matrix: 'Nueva matriz',
    eisenhower_matrix_name_ph: 'Nombre de la matriz (ej. Proyecto X)',
    pugh_new_matrix:      'Nueva matriz',
    pugh_matrix_name_ph:  'Nombre de la matriz (ej. Decisión Q1)',
    pugh_reference:       'Referencia',
    pugh_alternatives:    'Alternativas',
    pugh_criteria:        'Criterios',
    pugh_add_criterion:   'Agregar criterio',
    pugh_add_alternative: 'Agregar alternativa',
    pugh_score_better:    'Mejor (+1)',
    pugh_score_same:      'Igual (0)',
    pugh_score_worse:     'Peor (-1)',
    pugh_total:           'Total',
    pugh_weighted_total:  'Total ponderado',
    pugh_issue:           'Problema',
    pugh_datum:           'Referencia',
    pugh_weight:          'Peso',
    pugh_no_matrices:     'Aún no hay matrices. Crea una para empezar.',

    // ── Feed ──────────────────────────────────────────────────────────────────
    feed_title:       'Feed del Equipo',
    post_placeholder: '¿Qué tienes en mente?',
    post:             'Publicar',
    add_comment:      'Agrega un comentario…',
    comment:          'Comentar',
    no_posts:         '¡Aún no hay publicaciones. Sé el primero!',
    photo_url_optional:'URL de foto (opcional)',
    delete_post:      'Eliminar',
    replies_label:    'respuestas',
    share_ph:         '¿Qué tienes en mente? Comparte una actualización con tu equipo…',
    paste_img_ph:     'Pega una URL de imagen (ej. https://i.imgur.com/...)',
    remove_image_btn: 'Quitar imagen',
    add_image_btn:    'Agregar URL de imagen',
    no_posts_first:   '¡Aún no hay publicaciones. ¡Sé el primero en compartir algo!',
    comment_toggle:   'comentarios',
    add_a_comment_btn:'Agregar un comentario',
    write_comment_ph: 'Escribe un comentario… (Enter para enviar)',
    reply_btn:        'Responder',

    // ── Profile ───────────────────────────────────────────────────────────────
    my_profile_title:   'Mi Perfil',
    profile_visible:    'Este perfil es visible para todos los miembros. Haz clic en un campo para actualizarlo.',
    about_me:           'Acerca de mí',
    hobbies:            'Pasatiempos e Intereses',
    career:             'Carrera',
    semester:           'Semestre',
    university:         'Universidad',
    no_career:          'Sin carrera asignada',
    no_university:      'Sin universidad asignada',
    no_bio:             'Sin bio aún — haz clic para agregar una.',
    profile_photo:      'Foto de Perfil',
    cover_photo:        'Foto de Portada',
    reframe_profile:    'Reencuadrar',
    reframe_cover:      'Reencuadrar',
    edit_profile:       'Editar Perfil',
    display_name:       'Nombre para mostrar',
    email:              'Correo de contacto',
    email_placeholder:  'tu@ejemplo.com',
    profile_photo_url:  'URL de foto de perfil',
    cover_photo_url:    'URL de foto de portada',
    save_profile:       'Guardar Perfil',
    external_member:    'Externo',
    about_label:        'Acerca de mí',
    no_profile_info:    'Aún no se ha agregado información de perfil.',
    no_info:            'Sin información',
    member_not_found:   'Miembro no encontrado.',
    semester_suffix:    'semestre',
    semester_Faculty:   'Faculty',
    semester_Graduate:  'Posgrado',
    select_placeholder: '— seleccionar —',
    tell_team_placeholder:'Cuéntale a tu equipo sobre ti…',
    hobbies_placeholder:'Lectura, robótica, música…',

    // ── Profile — Misión ──────────────────────────────────────────────────────
    section_mission:           'Misión',
    current_objective:         '¿Qué estás construyendo?',
    current_challenge:         '¿Con qué estás luchando?',
    objective_ph:              'p.ej. Terminar el módulo de navegación autónoma…',
    challenge_ph:              'p.ej. Calibrar OpenCV correctamente…',
    no_mission_set:            'Sin misión registrada aún.',

    // ── Profile — Colaboración ─────────────────────────────────────────────────
    section_collaboration:     'Colaboración',
    looking_for_help_in:       'Busco ayuda en',
    i_can_help_with:           'Puedo ayudar con',
    skills_to_learn:           'Habilidades a aprender este semestre',
    skills_i_can_teach:        'Habilidades que puedo enseñar',
    collab_tags_ph:            'Busca o escribe para proponer…',
    collab_skill_hint:         'Busca una habilidad existente. Si no existe, puedes proponer una nueva.',
    skill_propose_new:         'Proponer nueva habilidad',
    skill_not_standardized:    'no estandarizado',
    skill_type_technical:      'Técnico',
    skill_type_learning:       'Aprendizaje',
    skill_type_support:        'Apoyo',
    skill_type_collaboration:  'Colaboración',
    skill_filter_all:          'Todas las habilidades',
    admin_skill_dictionary:    'Diccionario de habilidades',
    admin_skill_dictionary_hint:'Una por línea: id: etiqueta: tipo. Tipos: technical, learning, support, collaboration. Para perfil de colaboración.',
    tag_input_hint:            'Enter o coma para agregar · Backspace para quitar',
    tag_input_hint_suggestions:'Enter o coma para agregar · Escribe para ver sugerencias',
    no_collab_set:             'Sin información de colaboración aún.',
    looking_label:             'Necesita ayuda con',
    offering_label:            'Puede ayudar con',

    // ── Profile — Cultura ─────────────────────────────────────────────────────
    section_culture:           'Cultura',
    culture_what_i_listen:     'Lo que escucho',
    culture_book_that_marked:  'Libro que me marcó',
    culture_idea_that_motivates:'Idea que me motiva',
    culture_quote_that_moves:  'Frase que me mueve',
    culture_add:               '+ Agregar',
    song_on_repeat:            'Canción en repeat',
    song_title_label:          'Canción / Artista',
    song_url_label:            'Enlace (Spotify, YouTube…)',
    song_title_ph:             'p.ej. Power de Kanye West',
    song_url_ph:               'https://open.spotify.com/track/…',
    fun_fact_label:            'Dato curioso',
    fun_fact_ph:               'Comparte algo sorprendente sobre ti…',
    personality_tag_label:     'Soy…',
    no_culture_set:            'Sin información cultural aún.',
    invalid_song_url:          'El enlace debe ser de Spotify, YouTube o SoundCloud.',
    listen_link:               'Escuchar',

    // Personality tag options
    ptag_creative:       'Creativo/a',
    ptag_analytical:     'Analítico/a',
    ptag_detail:         'Orientado/a al detalle',
    ptag_bigpicture:     'Pensamiento global',
    ptag_solver:         'Resolvedor de problemas',
    ptag_collaborator:   'Colaborador/a',
    ptag_independent:    'Trabajo independiente',
    ptag_mentor:         'Mentor/a',
    ptag_learner:        'Aprendiz de por vida',
    ptag_builder:        'Constructor/a',
    ptag_researcher:     'Investigador/a',

    // ── Profile — Estatus semanal (presente continuo) ──────────────────────────
    section_weekly:          'Esta Semana',
    profile_logros_obtained:  'Logros obtenidos',
    profile_logros_empty:     'Sin logros aún. Publica actualizaciones semanales para ganar puntos (25 pts por cada una, 100 pts al llegar a 50).',
    profile_saved_merit_awarded: 'Perfil guardado. ¡+50 pts por Perfil completo!',
    profile_saved_merit_missing: 'Perfil guardado. Para el logro Perfil completo falta: bio, pasatiempos, objetivo, reto, etiquetas de colaboración (4), cultura (libro/idea/cita/música), etiqueta de personalidad y fecha de nacimiento.',
    weekly_merit_awarded: '¡+{pts} pts por Actualización semanal!',
    weekly_advanced:         'En qué estoy avanzando…',
    weekly_failed_at:        'En qué estoy fallando…',
    weekly_learned:          'Qué estoy aprendiendo…',
    weekly_ph_advanced:      '¿En qué estás avanzando?',
    weekly_ph_failed:        '¿En qué estás fallando?',
    weekly_ph_learned:       '¿Qué estás aprendiendo?',
    post_weekly_status:      'Publicar Estatus Semanal',
    update_weekly_status:    'Actualizar Esta Semana',
    no_weekly_status:        'Sin estatus publicado esta semana.',
    weekly_posted_by:        'Publicado por',
    week_of:                 'Semana',

    // ── Miembros — filtro de colaboración ─────────────────────────────────────
    filter_collab:           'Filtro de habilidades',
    collab_filter_ph:        'Filtrar por habilidad…',
    match_found:             'puede ayudar con esto',
    clear_skill_filter:      'Limpiar filtro',
    collab_match_hint:       'Coincidencia',

    // ── Join request modal ────────────────────────────────────────────────────
    join_title:              'Solicitar Unirse',
    join_pick_category:      'Selecciona tu área',
    join_motivation:         '¿Por qué quieres unirte? (opcional)',
    join_motivation_placeholder:'Cuéntanos sobre ti y tus objetivos…',
    join_send:               'Enviar Solicitud',
    join_category_required:  'Por favor selecciona un área.',
    which_category:          '¿A qué área deseas unirte?',
    no_categories_join:      'Aún no hay áreas — te asignarán una después.',
    why_join:                '¿Por qué quieres unirte?',
    optional_label:          '(opcional)',
    pending_review_note:     'Un admin del equipo revisará tu solicitud. Aparecerás en su lista de "Solicitudes Pendientes".',

    // ── Role labels ───────────────────────────────────────────────────────────
    role_aspirant:      'Aspirante',
    role_rookie:        'Novato',
    role_junior:        'Junior',
    role_senior:        'Senior',
    role_leader:        'Líder',
    role_facultyAdvisor:'Asesor Académico',
    role_teamAdmin:     'Admin de Equipo',

    // ── Image crop modal ──────────────────────────────────────────────────────
    drag_instruction:  'Arrastra para reposicionar · rueda del ratón o deslizador para zoom',
    image_loading_msg: 'Cargando…',
    image_error_msg:   'No se pudo cargar la imagen. Verifica la URL.',
    image_forbidden_url:'URL prohibida — Instagram y Facebook bloquean la incrustación.',
    image_blocked_host:'Las URLs de Instagram y Facebook bloquean la incrustación. Descarga la imagen y súbela a imgur.com o usa otra URL.',
    image_use_url:     'Usar URL sin recortar',
    image_select_file: 'Seleccionar archivo',
    image_crop_blocked:'No se puede recortar esta imagen (restricciones del sitio). Usa el enlace original.',
    image_fetching:    'Obteniendo imagen…',
    zoom_label:        'Zoom',
    apply_btn:         'Aplicar',
    remove_image:      'Quitar imagen',

    // ── Contribution path (Phase 5) ───────────────────────────────────────────
    path_section_title:     'Tu perfil de contribución',
    path_section_hint:      'Tendencias detectadas según tu actividad en el equipo.',
    path_view_evidence:     'Ver evidencia',
    path_hide_evidence:     'Ocultar evidencia',
    path_why:               'Por qué',
    path_technical_specialist: 'Especialista técnico',
    path_project_leader:    'Líder de proyecto',
    path_systems_integrator:'Integrador de sistemas',
    path_mentor_educator:   'Mentor / Educador',
    path_community_builder: 'Constructor de comunidad',
    path_researcher_innovator: 'Investigador / Innovador',
    path_evidence_merits:   'Logros',
    path_evidence_tasks:    'Tareas',
    path_evidence_modules:  'Módulos',
    channels_leave:         'Salir del canal',
    channels_delete:        'Eliminar canal',
    channels_no_available_teams: 'No hay equipos disponibles para invitar.',
    channels_confirm_accept:'Aceptar esta invitacion?',
    channels_confirm_decline:'Rechazar esta invitacion?',
    channels_confirm_invite:'Enviar estas invitaciones?',
    channels_confirm_leave:'Salir de este canal?',
    channels_confirm_delete:'Eliminar este canal y su historial? Esta accion no se puede deshacer.',
    channels_delete_failed:'No se pudo eliminar el canal.',
    channels_validation_name:'Escribe un nombre para el canal.',
    channels_status_owner:  'Fundador',
    channels_status_member: 'Miembro',
    channels_status_pending:'Pendiente',
    channels_status_declined:'Rechazado',
    channels_status_left:   'Salio',
    channels_history:       'Historial',
    channels_no_history:    'Sin movimientos previos.',
    channels_edit:          'Editar canal',
    channels_edit_help:     'Cambia el nombre o la descripcion del canal.',
    channels_invite_help:   'Selecciona equipos que todavia no forman parte del canal.',
    channels_pending_members: 'Invitaciones del canal',
    channels_no_pending_members: 'No hay invitaciones pendientes en este canal.',
    channels_pending_alert: 'Este canal tiene invitaciones pendientes. Los equipos invitados no podran participar hasta aceptar.',
    channels_message_failed:'No se pudo enviar el mensaje.',
    channels_messages_load_failed:'No se pudieron cargar los mensajes del canal.',
    channels_pending_notice:'Tu equipo aun tiene una invitacion pendiente. Acepta la invitacion para participar en este canal.',
    channels_readonly_notice:'El equipo activo no forma parte de este canal. Cambia de equipo o entra al canal para poder participar.',
  };
/** Lookup string by key. Returns STRINGS[k] or k. */
export const t = (k) => STRINGS[k] ?? k;

/** UI language (Spanish only). Use with getL/ensureString for bilingual data. */
export const lang = 'es';
